# Page settings

baseURL = "juanfran.rocks"
languageCode = "en"
title = "Joan's main page"
theme = "hugo-devresume-theme"
googleAnalytics = "G-EN1HZKED0E"


[params]
    author = "Joan Francesc Muñoz Martin"
    description = "Resume and Personal webpage"

    primaryColor = "#2986cc"
    textPrimaryColor = "#4b4b4b"

    [params.profile]
        enable = true
        name = "Joan F. Muñoz Martin"
        tagline = "Researcher, Technologist, Engineer"
        avatar = "avatar2.jpg"


    [params.contact]
        enable = true
        location = "Pasadena (USA) | Mallorca (Spain)"

        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:info@juanfran.rocks"
        text = "info@juanfran.rocks"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "https://juanfran.rocks"
        text = "https://juanfran.rocks"


    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "C/C++/Python/GoLang/MATLAB"
        [[params.skills.list.items]]
        details = "Node.js/PostgreSQL/MySQL/Git"
        [[params.skills.list.items]]
        details = "Altium"
        [[params.skills.list.items]]
        details = "Design, implement, and validation of embedded systems for science and technology advancements"
        [[params.skills.list.items]]
        details = "Lead and deliver complex engineering systems"
        
        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Critical thinker"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        [[params.skills.list.items]]
        details = "Good time management"

        [[params.skills.list]]
        title = "Metrics (2023)"
        [[params.skills.list.items]]
        details = "h-index: 13"
        [[params.skills.list.items]]
        details = "Manuscripts: 33"
        [[params.skills.list.items]]
        details = "Total Citations: 451"
        [[params.skills.list.items]]
        details = "Conference presentations: 25"
        


    [params.education]
        enable = true

        [[params.education.list]]
        degree = "PhD in Telecommunications Engineering (Nano-satellite design and Remote Sensing)"
        university = "Universitat Politècnica de Catalunya"
        dates = "2017 - 2021"
        [[params.education.list]]
        degree = "MSc in Telecommunications Engineering"
        university = "Universitat Politècnica de Catalunya"
        dates = "2014 - 2017"
        [[params.education.list]]
        degree = "BSc in Telecommunications Engineering"
        university = "Universitat Politècnica de Catalunya"
        dates = "2010 - 2014"


    [params.awards]
        enable = true

        [[params.awards.list]]
        name = "Best PhD thesis"
        body = "Three awards: UPC, IEEC, and IEEE GRSS"
        date = "2022 - 2023"
        [[params.awards.list]]
        name = "Group award for the first airborne campaign of a spectrometer for atmospheric sounding"
        body = "National Aeronautics and Space Administration"
        date = "2023"
        [[params.awards.list]]
        name = "Group award for the implementation of a spectrometer for atmospheric sounding"
        body = "Jet Propulsion Laboratory"
        date = "2022"
        [[params.awards.list]]
        name = "Group award for the contributions to cis-lunar space monitoring"
        body = "Jet Propulsion Laboratory"
        date = "2022"


    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "Spanish"
        level = "Native"
        [[params.languages.list]]
        name = "Catalan"
        level = "Native"
        [[params.languages.list]]
        name = "English"
        level = "Professional"



    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "CrossFit"
        [[params.interests.list]]
        name = "Sailing"
        [[params.interests.list]]
        name = "Hiking"
        [[params.interests.list]]
        name = "Space"



    [params.summary]
        enable = true
        text = "Telecommunications engineer with B.Sc., M.Sc., and Ph.D. degrees from UPC BarcelonaTech. Led remote sensing payloads for satellite missions at UPC NanoSat Lab. Collaborated with ESA on projects like BEXUS 19, Fly Your Satellite II, and 3Cat-5/FSSCat. Partook in GNSS-R experiment during MOSAiC. Researcher at NASA's JPL, focusing on GSSR signal processing, microwave radiometry, polarimetric GNSS-R, and innovative Earth observation instruments. Passionate about advancing space technology and instrumentation. Interested in quantum technologies for novel instruments."

    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Research Technologist"
        dates = "2022 - Present"
        company = "Jet Propulsion Laboratory"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis."
        [[params.experience.list.items]]
        details = "Lorem ipsum dolor sit amet, consectetuer."
        [[params.experience.list.items]]
        details = "Aenean commodo ligula eget dolor."
        [[params.experience.list.items]]
        details = "Etiam ultricies nisi vel augue."

        [[params.experience.list]]
        title = "Post-doctoral Fellow"
        dates = "2021 - 2022"
        company = "Jet Propulsion Laboratory"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel."
        [[params.experience.list.items]]
        details = "Lorem ipsum dolor sit amet, consectetuer."
        [[params.experience.list.items]]
        details = "Aenean commodo ligula eget dolor."

        [[params.experience.list]]
        title = "Pre-doctoral Fellow"
        dates = "2017 - 2021"
        company = "Universitat Politècnica de Catalunya"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.experience.list]]
        title = "Research Assistant"
        dates = "2014 - 2017"
        company = "Universitat Politècnica de Catalunya"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."

        [[params.experience.list]]
        title = "IT Assistant"
        dates = "2012"
        company = "Colegi Major Universitari Ramon Llull"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.experience.list]]
        title = "Administrative Assistant"
        dates = "2009"
        company = "Transports de les Illes Balears"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."




    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Cold Atom Laboratory"
        meta = "Jet Propulsion Laboratory"
        tagline = "Project description"

        [[params.projects.list]]
        title = "SMAP-Reflectometry"
        meta = "Jet Propulsion Laboratory"
        tagline = "Project description"

        [[params.projects.list]]
        title = "Goldstone Solar System Radar"
        meta = "Jet Propulsion Laboratory"
        tagline = "Project description"

        [[params.projects.list]]
        title = "Microwave Temperature and Humidity Probe"
        meta = "Jet Propulsion Laboratory"
        tagline = "Project description"

        [[params.projects.list]]
        title = "3Cat-4"
        meta = "Universitat Politècnica de Catalunya"
        tagline = "Project description"

        [[params.projects.list]]
        title = "FSSCat"
        meta = "Universitat Politècnica de Catalunya"
        tagline = "Project description"

        [[params.projects.list]]
        title = "MOSAiC"
        meta = "Universitat Politècnica de Catalunya"
        tagline = "Project description"


    [params.information]
        enable = true

        [[params.information.list]]
        title = "Selected Publications"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Climbing, Snowboarding, Photography, Travelling"






    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fa-brands fa-linkedin fa-2xl"
        url = "//linkedin.com/in/joan-francesc-munoz-martin"
        title = "joan-francesc-munoz-martin"
        [[params.social.list]]
        icon = "fa-brands fa-twitter fa-2xl"
        url = "//twitter.com/juanfmun"
        title = "@juanfmun"
        [[params.social.list]]
        icon = "fa-brands fa-orcid fa-2xl"
        url = "//orcid.org/0000-0002-6441-6676"
        title = "OrcID"
        [[params.social.list]]
        icon = "fa-brands fa-researchgate fa-2xl"
        url = "//www.researchgate.net/profile/Joan-Munoz-Martin"
        title = "ResearchGate"
        [[params.social.list]]
        icon = "fa-brands fa-github fa-2xl"
        url = "//github.com/juan0fran"
        title = "juan0fran"




